# Character creation screen
print("Welcome to Character Creation!")
player_name = input("What's your character's name? ")
player_class = input("Pick a class (warrior, mage, archer): ")
Favorite_weapon = input("What's your favorite weapon? ")
player_level = input("what is your level?")
print("Loading your character...")
print(f"{player_class} is ready for battle!")
print(player_level)
print(type(player_level))